# Generated by Django 2.2.10 on 2020-02-27 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_galleryimage_infocard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='infocard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='home.InfoCard'),
        ),
    ]
