# Generated by Django 2.2.10 on 2020-02-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0007_auto_20200227_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocard',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Bild'),
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
